name: CI/CD for Azure Function with Terraform

on:
  push:
    branches:
      - main

permissions:  
  id-token: write  # Required for OIDC authentication with Azure  
  contents: read   # Default read access to repo contents  

jobs:
  terraform:
    name: Terraform Infrastructure Deployment
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # for TF Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
      # if manualy deploying not TF then this is required!
      # - name: Login to Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        
      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform
        
      - name: Terraform Apply (Infrastructure Deployment)
        run: terraform apply -auto-approve
        working-directory: terraform
        
      - name: Capture Terraform Outputs
        run: |
          echo "FUNC_APP_NAME=$(terraform output -raw function_app_name)" >> $GITHUB_ENV
          echo "FUNC_APP_URL=$(terraform output -raw function_app_url)" >> $GITHUB_ENV
          # Do NOT expose system key directly in logs!
          echo "::add-mask::$(terraform output -raw function_app_system_key)"
        working-directory: terraform
      
      - name: Print Function App Details (without exposing secrets)
        run: |
          echo "Function App Name: $FUNC_APP_NAME"
          echo "Function App URL: $FUNC_APP_URL"

  tests:
    name: Run Unit Tests for Azure Function
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Pytest Unit Tests
        run: pytest tests/ --junitxml=pytest_report.xml

      - name: Upload Test Report (if failure)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: pytest-report
          path: pytest_report.xml

  deploy-function:
    name: Deploy Azure Function
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python Environment
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy Function to Azure
        run: func azure functionapp publish $FUNC_APP_NAME
